export const WEEK_2022_05_22 = [
  {
    position: 1,
    name: 'BBB Academy',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: -2,
    points: 3,
    form: ['w', 'l', 'w', 'l', 'd'],
  },
  {
    position: 2,
    name: 'Chelsea',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: 0,
    points: 3,
    form: ['l', 'l', 'l', 'l', 'l'],
  },
  {
    position: 3,
    name: 'Real Sociedad',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: 2,
    points: 3,
    form: ['d', 'd', 'd', 'd', 'd'],
  },
  {
    position: 4,
    name: 'Manchester',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: 2,
    points: 3,
    form: ['w', 'w', 'w', 'w', 'w'],
  },
  {
    position: 5,
    name: 'Los primos',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: 2,
    points: 3,
    form: ['w', 'w', 'w', '', ''],
  },
  {
    position: 6,
    name: '11 lobos',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: 2,
    points: 3,
    form: ['d', 'd', 'w', 'l', 'd'],
  },
  {
    position: 7,
    name: 'murcielagos',
    played: 1,
    won: 1,
    drawn: 0,
    lost: 0,
    gf: 5,
    ga: 3,
    gd: 2,
    points: 3,
    form: ['', '', '', '', ''],
  },
]
